cc_binary(
    name = "task3",
    srcs = [
        "3-main.c",
    ],
    deps = [":lists"],
)

cc_library(
    name = "lists",
    srcs = [
        "0-print_dlistint.c",
        "3-add_dnodeint_end.c",
        "4-free_dlistint.c",
        "5-get_dnodeint.c",
        "6-sum_dlistint.c",
        "7-insert_dnodeint.c",
    ],
    hdrs = ["lists.h"],
    deps = [],
)

cc_binary(
    name = "task4",
    srcs = [
        "4-main.c",
    ],
    deps = [":lists"],
)

cc_binary(
    name = "task5",
    srcs = [
        "5-main.c",
    ],
    deps = [":lists"],
)

cc_binary(
    name = "task6",
    srcs = [
        "6-main.c",
    ],
    deps = [":lists"],
)

cc_binary(
    name = "task7",
    srcs = [
        "7-main.c",
    ],
    deps = [":lists"],
)
